
  
name: "Release"

on:
  push:
    branches:
      - '*/*'
      - 'r/**'
      - 'r/categories'
      - 'r/messages_chain'

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
 
     
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{github.ref_name}}"
          prerelease: false
          title: "${{github.ref_name}}"
          files: |
            LICENSE
            *.jar
